# Generated by Django 3.2.3 on 2023-04-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default=None, max_length=20)),
                ('precio', models.CharField(default=None, max_length=70)),
                ('descripcion', models.CharField(default=None, max_length=70)),
                ('cantidad', models.CharField(default=None, max_length=70)),
                ('categoria', models.CharField(default=None, max_length=70)),
            ],
        ),
    ]
