# Generated by Django 3.2.3 on 2023-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_auto_20230419_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(),
        ),
    ]
