# Generated by Django 3.2.3 on 2023-04-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10),
        ),
    ]
