# Generated by Django 3.2.3 on 2023-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membresias', '0004_auto_20230514_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='fecha_limite',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pago',
            name='iva',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='subtotal',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_cliente',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='pago',
            name='precio_pago',
            field=models.FloatField(default=None),
        ),
    ]
